export function cards() {
  const cards = [
    {
      id: 0,
      title: "Silent Wave",
      persona: "Creator",
      type: "standard",
      imageMain: "src/assets/card/art01.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "black", "art"],
      value: 1.5,
      dolar: 2.683,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
    {
      id: 1,
      title: "Silent Color",
      persona: "Creator102",
      type: "standard",
      imageMain: "src/assets/card/art02.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "art"],
      value: 1.55,
      dolar: 2.773,
      describe:
        "On Foundation, anyone can create a profile to start collecting NFTs. All you’ll need is a MetaMask wallet and ETH, the cryptocurrency used to pay for all transactions on Ethereum. Artists list NFTs for auction at a reserve price, and once the first bid is placed, a 24-hour auction countdown begins. If a bid is placed within the last 15 minutes, the auction extends for another 15 minutes.",
    },
    {
      id: 2,
      title: "Pawel Czerwinski",
      persona: "Pawel Czerwinski",
      type: "hot",
      imageMain: "src/assets/card/art03.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "black", "art"],
      value: 1.03,
      dolar: 2.201,
      describe:
        "On Foundation, anyone can create a profile to start collecting NFTs. All you’ll need is a MetaMask wallet and ETH, the cryptocurrency used to pay for all transactions on Ethereum. Artists list NFTs for auction at a reserve price, and once the first bid is placed, a 24-hour auction countdown begins. If a bid is placed within the last 15 minutes, the auction extends for another 15 minutes.",
    },
    {
      id: 3,
      title: "Man Wave",
      persona: "Openart",
      type: "hot",
      imageMain: "src/assets/card/art04.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "draw", "art"],
      value: 1.52,
      dolar: 2.707,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
    {
      id: 4,
      title: "Calice",
      persona: "Openart",
      type: "hot",
      imageMain: "src/assets/card/art05.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "art"],
      value: 1.0,
      dolar: 2.502,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
    {
      id: 5,
      title: "Mirror",
      persona: "Openart",
      type: "hot",
      imageMain: "src/assets/card/art06.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "draw", "art"],
      value: 1.52,
      dolar: 2.707,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
    {
      id: 6,
      title: "Shedd Aquarium",
      persona: "Openart",
      type: "hot",
      imageMain: "src/assets/card/art07.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "draw", "art"],
      value: 1.41,
      dolar: 2.599,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
    {
      id: 7,
      title: "Family Lego",
      persona: "Openart",
      type: "hot",
      imageMain: "src/assets/card/art08.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "draw"],
      value: 1.81,
      dolar: 3.0,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
    {
      id: 8,
      title: "Green Paint",
      persona: "Creator",
      type: "standard",
      imageMain: "src/assets/card/hot-art01.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "black", "art"],
      value: 1.5,
      dolar: 2.683,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
    {
      id: 9,
      title: "Field woman",
      persona: "Lucia Almeida",
      type: "standard",
      imageMain: "src/assets/card/hot-art02.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "art"],
      value: 1.55,
      dolar: 2.773,
      describe:
        "On Foundation, anyone can create a profile to start collecting NFTs. All you’ll need is a MetaMask wallet and ETH, the cryptocurrency used to pay for all transactions on Ethereum. Artists list NFTs for auction at a reserve price, and once the first bid is placed, a 24-hour auction countdown begins. If a bid is placed within the last 15 minutes, the auction extends for another 15 minutes.",
    },
    {
      id: 10,
      title: "Bubbles",
      persona: "Akan Park",
      type: "standard",
      imageMain: "src/assets/card/hot-art03.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "black", "art"],
      value: 1.03,
      dolar: 2.201,
      describe:
        "On Foundation, anyone can create a profile to start collecting NFTs. All you’ll need is a MetaMask wallet and ETH, the cryptocurrency used to pay for all transactions on Ethereum. Artists list NFTs for auction at a reserve price, and once the first bid is placed, a 24-hour auction countdown begins. If a bid is placed within the last 15 minutes, the auction extends for another 15 minutes.",
    },
    {
      id: 11,
      title: "hot iron",
      persona: "Dennis Travel",
      type: "standard",
      imageMain: "src/assets/card/hot-art04.png",
      imagePersona: "src/assets/card/person.png",
      definitions: ["color", "circle", "draw", "art"],
      value: 1.52,
      dolar: 2.707,
      describe:
        "Together with my design team, we designed this futuristic Cyberyacht concept artwork. We wanted to create something that has not been created yet, so we started to collect ideas of how we imagine the Cyberyacht could look like in the future.",
    },
  ];

  return cards;
}
